### ISSUE TITLE
fos-zenoh service error when starting the service due to "invalid id"

### ISSUE THREAD

**Issue by lewisfelix** [eclipse-fog05/fog05#212]
Good evening:

After installing all the components of Fog05 from source, when running the fos-zenoh agent as requested in the guide (sudo systemctl start zenoh) it does not start due to a "failed" state. Running "journalctl -u fos-zenoh -f" shows the following error:

`fog05 fos-zenoh[1304]: zenoh error: (Invalid id: a7e09739-4a9a-4359-9f1f-530406875a45 - Invalid character '-' at position 8) at zenoh-router/src/runtime/mod.rs:45.. Exiting...`

I installed the latest zenoh router (_zenohd_0.5.0~beta.5_). Could you provide more information about this error?

This installation is being performed in a Debian 10 (buster) virtual machine.

Thank you so much.

**Comment by gabrik** [comment]
Hi @lewisfelix,

I guess it happens because of a fix introduced in Zenoh after the release.

You could try to generate the Zenoh debian packages and install (apt install --reinstall ./<path to deb files>) the latest zenoh from master.

The steps should be:

```
git clone https://github.com/eclipse-zenoh/zenoh
cd zenoh
cargo deb -p zenoh-router
cargo deb -p zenoh-storages
```
The deb packages then should be inside `target/debian/`

I hope this helps you

**Comment by lewisfelix** [comment]
Hello @gabrik 

It worked like a charm! Perhaps the reason was exactly what you have mentioned. Installing the latest version from zenoh master has solved it.

Thank you so much!
